version = 0.1
[default.deploy.parameters]
stack_name = "sam-2015"
resolve_s3 = true
s3_prefix = "sam-2015"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
