name: Publish docker images

on:
  push:
  workflow_dispatch:

jobs:
  build_and_deploy_everywhere:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build . -t ${{ secrets.AWS_ACCOUNT_URL }}/${{ vars.AWS_ECR }}:$rev
          rev=$(git rev-parse --short HEAD)
      - name: Deploy to aws ECR
        if: github.ref_name == 'main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
        run: |
          aws ecr get-login-password | docker login -u AWS --password-stdin ${{ secrets.AWS_ACCOUNT_URL }}/${{ vars.AWS_ECR }}
          rev=$(git rev-parse --short HEAD)
          docker push ${{ secrets.AWS_ACCOUNT_URL }}/${{ vars.AWS_ECR }}:$rev
